-- No-op.
-- This migration was originally created before the base init migration and would
-- fail on a fresh database because the "Location" table did not exist yet.
-- The safe additive ALTER now runs in a later migration after init.
