CREATE TABLE "Place" (
  "id" TEXT NOT NULL,
  "googlePlaceId" TEXT,
  "name" TEXT NOT NULL,
  "address" TEXT,
  "city" TEXT,
  "country" TEXT,
  "neighborhood" TEXT,
  "category" TEXT NOT NULL,
  "shortFormattedAddress" TEXT,
  "googleTypes" TEXT[] DEFAULT ARRAY[]::TEXT[],
  "googlePrimaryType" TEXT,
  "googlePrimaryTypeDisplayName" TEXT,
  "latitude" DOUBLE PRECISION,
  "longitude" DOUBLE PRECISION,
  "rating" DOUBLE PRECISION,
  "userRatingCount" INTEGER,
  "priceLevel" INTEGER,
  "openingHours" TEXT[] DEFAULT ARRAY[]::TEXT[],
  "currentOpeningHours" TEXT[] DEFAULT ARRAY[]::TEXT[],
  "servesBreakfast" BOOLEAN,
  "servesLunch" BOOLEAN,
  "servesDinner" BOOLEAN,
  "servesBeer" BOOLEAN,
  "servesWine" BOOLEAN,
  "servesBrunch" BOOLEAN,
  "servesDessert" BOOLEAN,
  "servesCoffee" BOOLEAN,
  "servesCocktails" BOOLEAN,
  "goodForGroups" BOOLEAN,
  "goodForWatchingSports" BOOLEAN,
  "outdoorSeating" BOOLEAN,
  "mapsUrl" TEXT,
  "websiteUri" TEXT,
  "primaryImageUrl" TEXT,
  "lastGoogleFetchedAt" TIMESTAMP(3),
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

  CONSTRAINT "Place_pkey" PRIMARY KEY ("id")
);

CREATE UNIQUE INDEX "Place_googlePlaceId_key" ON "Place"("googlePlaceId");
